name: React build
on: 
  push:                               # master Branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code.   # 레포지토리 체크아웃
        uses: actions/checkout@main

      - name: Install Dependencies    # 의존 파일 설치
        run: yarn install

      - name: Build                   # React Build
        run: npm run build
      - name: Deploy to gh-pages 
        run: |
          git config --global user.name 'LimFull'
          git config --global user.email 'full7002@naver.com'
          git add build/
          git commit -am "Auto build"
          git subtree split --branch gh-pages --prefix build/ 
          git push -f origin gh-pages:gh-pages
          git branch -D gh-pages
